USE bcy3db;

DROP TABLE IF EXISTS messages;
CREATE TABLE messages(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(50),
`from` VARCHAR(50),
body TEXT,
created DATETIME,
modified DATETIME,
user_id INT UNSIGNED
);

DROP TABLE IF EXISTS users;
CREATE TABLE users(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50),
password TEXT,
created DATETIME,
modified DATETIME
);

DROP TABLE IF EXISTS reviews;
CREATE TABLE reviews(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(50),
body TEXT,
rating INT UNSIGNED,
media VARCHAR(50),
created DATETIME,
modified DATETIME,
user_id INT UNSIGNED
);

DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
body TEXT,
created DATETIME,
modified DATETIME,
user_id INT UNSIGNED
);
